version: "3"

services:
  mongodb:
    image: mongo:4.4.14
    container_name: mongodb
    restart: on-failure
    volumes:
      - ./.docker/mongodb/mongod.conf:/etc/mongod.conf
      - ./.docker/mongodb/initdb.d:/docker-entrypoint-initdb.d
      - ./.docker/mongodb/data/db:/data/db
      - ./.docker/mongodb/data/log:/var/log/mongodb
    env_file:
      - .env
    environment:
      MONGO_REPLICA_SET_NAME: ${MONGO_REPLICA_SET_NAME:-rs0}
    ports:
      - 27017:27017
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command:
      [
        "/usr/bin/mongod",
        "--replSet",
        "${MONGO_REPLICA_SET_NAME:-rs0}",
        "--bind_ip_all",
      ]
